### ISSUE TITLE
suggestion: use a native golang git library instead of binary 

### ISSUE THREAD

**Issue by DataHearth** [sharpvik/sema#10]
Hey! I've been browsing your code to understand how to build up `sema` and I came across the git section in [agent/agent.go](https://github.com/sharpvik/sema/blob/main/agent/agent.go). 

I think using a native golang git library would be a great addition as you'll abstract `sema` from the `git` binary (which may differ from a system to another).

I've been using [this](https://github.com/go-git/go-git) library (which is listed on the `git-scm` website). It's a great and efficient library. 
This should be simple to implement as you don't extensively rely on git commands.

**Comment by sharpvik** [comment]
That's a great suggestion! However, I cannot figure out how to properly implement the `git add .` operation that is so dear to my heart. If you delete a file in a repo, running

```go
// `sema -a` will result in the following:
a.workTree.AddGlob(".")
```

will not actually stage that deletion (at least on my computer). Please see [this file](https://github.com/sharpvik/sema/blob/refactor/use-go-git/agent/agent.go#L66) to review my failed attempt.

I have created [this PR](https://github.com/sharpvik/sema/pull/13) to work on the issue and I'd really appreciate your help with this one since you already have experience with the library.

Have you got any spare time to help?

**Comment by DataHearth** [comment]
Hmmm, so the problem is still there... I've found an already opened [issue](https://github.com/go-git/go-git/issues/223) relating this problem. It also has a PR but it hasn't beed merged yet...
I'm gonna ping the PR and the issue.

My workaround was to use (unfortunatly) the `git` binary just for this operation. 
BUT, I've found [this comment](https://github.com/go-git/go-git/issues/332#issuecomment-1108253405) giving a good workaround. I haven't tested yet.

**Comment by DataHearth** [comment]
Ok, it seems to work :). Here's how I did it 
```go
w, err := r.repository.Worktree()
if err != nil {
	return err
}

status, err := w.Status()
if err != nil {
	return err
}

for file := range status {
    _, err = w.Add(file)
    if err != nil {
        return err
    }
}
```
You first get your working tree then get its status (equivalent to `git status`). Then you loop through each file and add them one by one. After, you should be good to go :)

**Comment by sharpvik** [comment]
Thanks so much for this, @DataHearth. I've rewritten most of the functionality by now. Last question (I hope): is there a way to enact `git push`? I don't seem to find a function with that name.

**Comment by DataHearth** [comment]
Sure ! You can use your repository to push changes
```go
repo, err := git.PlainOpen(".")
...
// add your thing, status, worktree, etc

err := repo.Push(&git.PushOptions{})
```

There you go :)

**Comment by sharpvik** [comment]
What about authentication, @DataHearth? When I used this method, I get

```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Am I supposed to parse git configs myself to get this to work?

**Comment by DataHearth** [comment]
Hey, I encoutered another issue (but quite similar to this one actually) a while ago and resolved it using this issue https://github.com/go-git/go-git/issues/411
