### ISSUE TITLE
Configure a list of known scopes

### ISSUE THREAD

**Issue by jamesfoster** [sharpvik/sema#14]
Is it possible to configure sema to provide a list of options for "scope". I'm thinking some kind of well known file name it scans the directory structure for. `.semantic-commit` ? You could even use it to filter the list of allowed "types" by file type or folder?

```
.semantic-commit
----------------
{
  scopes: ["auth", "api", "ui", "parser", ...],
  types: [{
    paths: ["/docs", "*.md"],
    allowedTypes: ["docs", "chore", "style"],
    defaultType: "docs"
  }, ...]
}
```

**Comment by sharpvik** [comment]
One could probably do that, however, I'm not sure if juice is worth the squeeze in this case. Why would you require such precision? Could you come up with a use case where this is absolutely necessary?

**Comment by sharpvik** [comment]
Stale issue.
