### ISSUE TITLE
Implement `--no-verify` flag

### ISSUE THREAD

**Issue by kbiits** [sharpvik/sema#15]
Would it be nice if we can pass flags (options) to the git commit command ?

usecase example : 
when I want to skip githooks, I will use git commit --no-verify. But with sema, I can't do that, because there's no way to pass the options to git

**Comment by sharpvik** [comment]
With the introduction of `v2.0.0`, sema does not rely on the `git` binary for its commit functionality. We use `git-go` library under the hood, which probably means we have to implement each flag by hand? I am not sure if there is a more elegant solution here, @kbiits. Would you like to look into it and compose a PR?

**Comment by DataHearth** [comment]
Hey, we can dynamically set commit flags, but we still need to create an array with wanted flags.
I think we can just look at what flags are available with `go-git` and implement a maximum of them or the most relevant ones.

I can do it if we define the context 😄.

**Comment by sharpvik** [comment]
@kbiits I've renamed this issue and put it into [this project board](https://github.com/users/sharpvik/projects/2). However, I understand that this is not exactly what you asked for.

The current ideology of `sema` is that it is not a direct replacement for git but a lightweight tool that makes _some_ operations more convenient and quick. For that reason, we don't want to allow all `git-commit` flags to be applied to `sema` but a select few that are most frequently used. The `--no-verify` is one such flag and we will bring it in shortly.

For a discussion about other flags, please see [this discussion](https://github.com/users/sharpvik/projects/2/)!
