### ISSUE TITLE
Implement `--push` flag using go-git

### ISSUE THREAD

**Issue by sharpvik** [sharpvik/sema#16]
As discussed earlier, some work has to be done to reliably implement `--push` functionality using `git-go`. Would you like to look into it, @DataHearth?

**Comment by DataHearth** [comment]
Hey! I can do it :). Should be quick. I already did it on my project. Gonna send you a PR when I'm done 👍

**Comment by sharpvik** [comment]
This implementation leads to errors regarding SSH keys that do not appear when using `git push`. Needs more investigation. Reopening this issue and moving card into **To Do** column in project.
