### ISSUE TITLE
Implement the `--upstream` flag

### ISSUE THREAD

**Issue by sharpvik** [sharpvik/sema#9]
On the first push to upstream, the `--push` will always fail due to the absence of upstream branch records. Maybe this could be fixed with the introduction of the `--upstream | -u` flag?

**Comment by DataHearth** [comment]
This can relate to #15 by adding more git flags.
@sharpvik do you have a way to discuss about it ? (Github discussion, discord...)

**Comment by sharpvik** [comment]
@DataHearth my personal discord is sharpvik#0320 text me there.

**Comment by DataHearth** [comment]
Flag shouldn't be necessary. After few tests, `go-git` seems to do it automatically.

**Comment by sharpvik** [comment]
Should we close this then @DataHearth ?
